
name: vibego_app
description: A short-form video app with email & phone sign-in.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0

flutter:
  assets:
    - assets/logo.png
